server.port=8081

spring.application.name=config-service
spring.cloud.config.server.git.default-label=property-acq
spring.cloud.config.server.git.uri=https://github.com/kmontes198910/config_servise
spring.cloud.config.server.git.search-paths=config-data
spring.cloud.config.server.git.username=kmontes198910
spring.cloud.config.server.git.password=${GITHUB_TOKEN}
eureka.instance.hostname=registry
eureka.client.service-url.defaultZone=${SERVER-EUREKA:http://registry-service:8761/eureka}

