apiVersion: v1
kind: Service
metadata:
  name: digital-signature-service
  namespace: medinec-dev
spec:
  selector:
    app: digital-signature
  ports:
    - protocol: TCP
      port: 8090               # Puerto del servicio (puerto lógico al que se conectan otros servicios)
      targetPort: 8090         # Puerto expuesto por el contenedor
  type: ClusterIP              # Tipo de servicio para comunicación interna en el clúster