apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: medinec-dev
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 8671
      targetPort: 8671
  type: ClusterIP