apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: medinec-dev
spec:
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  selector:
    app: medinec-registry  # 👈 CORREGIDO PARA COINCIDIR CON EL DEPLOYMENT
  type: ClusterIP