apiVersion: v1
kind: Service
metadata:
  name: rrhh-service
  namespace: medinec-dev
spec:
  selector:
    app: rrhh
  ports:
    - protocol: TCP
      port: 9909               # Puerto del servicio (puerto lógico al que se conectan otros servicios)
      targetPort: 9909       # Puerto expuesto por el contenedor
  type: ClusterIP            # Puedes cambiar a NodePort o LoadBalancer si necesitas acceso externo