apiVersion: v1
kind: Secret
metadata:
  name: config-secret
  namespace: medinec-dev
type: Opaque
data:
  RC_ACTIVE_PROFILE: ZGV2
  spring.cloud.config.server.git.username: a21vbnRlczE5ODkxMA==
  spring.cloud.config.server.git.password: Z2hwX04yb3FLRHUxekpGMEdaaWxPUkpOamJocGs3bEZYRjJsbERtOA==