spring.application.name=medical-test
spring.profiles.active=${RC_ACTIVE_PROFILE:default}
spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081
server.port=9825

# Config Server settings
spring.cloud.config.fail-fast=true
spring.cloud.config.retry.initial-interval=1500
spring.cloud.config.retry.max-attempts=10
spring.cloud.config.retry.max-interval=1000

# Eureka settings
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.preferIpAddress=true

