apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-test
  namespace: medinec-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-medical-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: medical-test
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-medical-test
    spec:
      containers:
        - name: medical-test
          image: kmontes2020/medinec-medical-test-dev:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9909
              protocol: TCP
          envFrom:
            - secretRef:
                name: medical-test-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: medical-test
  namespace: medinec-dev
spec:
  selector:
    app: medical-test
  ports:
    - protocol: TCP
      port: 9909
      targetPort: 9909
  type: ClusterIP