spring.application.name=wa-messaging
server.port=9701

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:6432/doctorkyn-dev?currentSchema=wamessaging
spring.datasource.username=medinec_rw
spring.datasource.password=EB0vIG6WNOJLXd5mtjr7fddmCvP8txyN
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# WhatsApp API Configuration
whatsapp.api.url=https://graph.facebook.com
whatsapp.api.phone-number-id=541998385660923
whatsapp.api.token=EAASZBIars1UABO1vaNiZCUrMMfkeRnWr1SLl1mZCkHl07vH4ZAE9Li7ZChoBkemHnwZAVZAgFmUEI8eW5v3NnJyZAUb0GcAFkEnEcAEBMoCC0sFrYJG2fglZCeyZCZA1vtoaiB1Bddx2F5jl1yU3cipHkYoRvmCWZCk1wWA5w8DlWXCK8C9ZBZC9refFNEZBjrRWNVt2EFcVdQJErwtTbx1aqjQMczr8YMTflUZD
whatsapp.api.version=v22.0
whatsapp.webhook.verify-token=medinec-whatsapp-webhook-token

# Thread Pool Configuration for Concurrent Message Processing
wa.messaging.thread.core-pool-size=10
wa.messaging.thread.max-pool-size=50
wa.messaging.thread.queue-capacity=500
wa.messaging.thread.name-prefix=wa-message-processor-

# Cola interna de mensajes
wa.messaging.queue.poll-interval=100
wa.messaging.queue.batch-size=10
wa.messaging.retry.max-attempts=3
wa.messaging.retry.delay=60000

# Configuración de Springdoc OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true
