spring.application.name=surgery
spring.profiles.active=${RC_ACTIVE_PROFILE:default}
spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081

spring.read-datasource.minimum-idle=1
spring.read-datasource.maximum-pool-size=2
spring.read-datasource.idle-timeout=10000
spring.read-datasource.max-lifetime=300000
spring.read-datasource.connection-timeout=10000
spring.read-datasource.leak-detection-threshold=60000
spring.read-datasource.pool-name=SurgeryReadHikariPool
spring.read-datasource.auto-commit=false

spring.datasource.minimum-idle=1
spring.datasource.maximum-pool-size=2
spring.datasource.idle-timeout=10000
spring.datasource.max-lifetime=300000
spring.datasource.connection-timeout=10000
spring.datasource.leak-detection-threshold=60000
spring.datasource.pool-name=SurgeryWriteHikariPool
spring.datasource.auto-commit=false