apiVersion: apps/v1
kind: Deployment
metadata:
  name: cirugia
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-cirugia
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: cirugia
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-cirugia
    spec:
      containers:
        - name: cirugia
          image: kmontes2020/medinec-cirugia:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9901
              protocol: TCP
          envFrom:
            - secretRef:
                name: cirugia-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: cirugia-service
  namespace: medinec
spec:
  selector:
    app: cirugia
  ports:
    - protocol: TCP
      port: 9909           # Puerto externo expuesto por el servicio
      targetPort: 9909   # Puerto donde está escuchando el contenedor
  type: ClusterIP        # Tipo de servicio (puedes cambiar a NodePort o LoadBalancer si es necesario)