apiVersion: apps/v1
kind: Deployment
metadata:
  name: digital-signature
  namespace: property-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-property-prod-digital-signature
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: digital-signature
        workload.user.cattle.io/workloadselector: apps.deployment-property-prod-digital-signature
    spec:
      containers:
        - name: digital-signature
          image: kmontes2020/property-digital-signature:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9909
              protocol: TCP
          envFrom:
            - secretRef:
                name: digital-signature-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: digital-signature
  namespace: property-prod
spec:
  selector:
    app: digital-signature
  ports:
    - protocol: TCP
      port: 9909
      targetPort: 9909
  type: ClusterIP