apiVersion: apps/v1
kind: Deployment
metadata:
  name: patients-evaluation
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-patients-evaluation
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: patients-evaluation
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-patients-evaluation
    spec:
      containers:
        - name: patients-evaluation
          image: kmontes2020/medinec-patients-evaluation:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9902
              protocol: TCP
          envFrom:
            - secretRef:
                name: patients-evaluation-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: patients-evaluation-service
  namespace: medinec
spec:
  selector:
    app: patients-evaluation-secret
  ports:
    - protocol: TCP
      port: 9902           # Puerto externo expuesto por el servicio
      targetPort: 9902   # Puerto donde está escuchando el contenedor
  type: ClusterIP        # Tipo de servicio (puedes cambiar a NodePort o LoadBalancer si es necesario)