apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-internal
  namespace: medinec
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-payment-internal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: payment-internal
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-payment-internal
    spec:
      containers:
        - name: payment-internal
          image: kmontes2020/medinec-payment-internal:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9901
              protocol: TCP
          envFrom:
            - secretRef:
                name: payment-internal-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: payment-internal-service
  namespace: medinec
spec:
  selector:
    app: payment-internal
  ports:
    - protocol: TCP
      port: 9901           # Puerto externo expuesto por el servicio
      targetPort: 9901   # Puerto donde está escuchando el contenedor
  type: ClusterIP        # Tipo de servicio (puedes cambiar a NodePort o LoadBalancer si es necesario)