apiVersion: apps/v1
kind: Deployment
metadata:
  name: treatments
  namespace: medinec
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"name":"treatments","namespace":"medinec"}}
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-medinec-treatments
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-medinec-treatments
    spec:
      containers:
        - name: treatments
          image: kmontes2020/medinec-treatments:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 9906
              protocol: TCP
          envFrom:
            - secretRef:
                name: treatments-secret
      imagePullSecrets:
        - name: dokcer-hub
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: treatments-service
  namespace: medinec
spec:
  ports:
    - protocol: TCP
      port: 9909         # Puerto expuesto para el servicio
      targetPort: 9909 # Puerto interno del contenedor
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-medinec-treatments
  type: ClusterIP