apiVersion: v1
kind: Service
metadata:
  name: cloudbridges-service
  namespace: medinec
spec:
  selector:
    app: cloudbridges
  ports:
    - protocol: TCP
      port: 9909          # Puerto en el servicio
      targetPort: 9909    # Puerto en el contenedor
  type: ClusterIP      # Cambia a NodePort o LoadBalancer si necesitas acceso externo