spring.application.name= treatments
spring.profiles.active=${RC_ACTIVE_PROFILE:default}
#spring.profiles.active=${RC_ACTIVE_PROFILE:dev}
spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081
#spring.cloud.config.username=root
#spring.cloud.config.password=S3cr3tp4swordConf1G

# Forzar explícitamente el uso de modo servlet (Spring MVC)
spring.main.web-application-type=servlet

# Configuración de Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
