spring.application.name=invoice
spring.profiles.active=${RC_ACTIVE_PROFILE:default}
spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081

# Desactivar open-in-view para evitar la advertencia
spring.jpa.open-in-view=false

# Configuración explícita para usar Spring MVC
spring.main.web-application-type=servlet

# Desactivar verificación de ubicación de plantillas Thymeleaf
spring.thymeleaf.check-template-location=false