spring.application.name=digitalSignature
server.port=9701
spring.profiles.active=${RC_ACTIVE_PROFILE:default}
spring.config.import=configserver:http://${RC_SERVER_CONFIG:localhost}:8081

# Configuración para el servicio de firma digital
signature.keystore.path=classpath:keystore.p12
signature.keystore.password=changeit
signature.keystore.default.alias=default

# Configuración de logging
logging.level.com.kynsoft.finamer.digitalsignature=DEBUG
