spring:
  application:
    name: digitalSignature
server:
  port: 9701

# Configuración para el servicio de firma digital
signature:
  keystore:
    path: classpath:keystore.p12
    password: changeit
    default:
      alias: default

# Configuración de Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Configuración de logging
logging:
  level:
    com.kynsoft.finamer.digitalsignature: DEBUG