apiVersion: v1
kind: Service
metadata:
  name: digital-signature-service
  namespace: medinec
spec:
  selector:
    app: digital-signature  # Coincide con las etiquetas del Deployment
  ports:
    - protocol: TCP
      port: 8090      # Puerto del servicio dentro del cluster
      targetPort: 8090  # Puerto dentro del contenedor
  type: ClusterIP  # Mantiene el servicio interno en el cluster