apiVersion: v1
kind: Service
metadata:
  name: rrhh-service
  namespace: medinec
spec:
  selector:
    app: rrhh  # Coincide con las etiquetas del Deployment
  ports:
    - protocol: TCP
      port: 9909      # Puerto del servicio dentro del cluster
      targetPort: 9909  # Puerto dentro del contenedor
  type: ClusterIP  # Mantiene el servicio interno en el cluster